baseurl = "https://data-analytics.netlify.com/"
title = "Web Archive"
languageCode = "en-us"
paginate = "5" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-22322985-3" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Thomas Laber"
  # bio = "\"Failure is not an option. \n Everyone has to succeed.\" - Arnold Schwarzenegger"
  bio = "\"If it bleeds, we can kill it.\" - Arnold Schwarzenegger" 
  avatar = "img/_misc/tl.jpg"

[Params]
  subtitle = "Thomas Laber" # Subtitle of your site
  description = "Thomas Laber's personal blog about everything" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  # toc = true # Enable Table of Contents
  post_navigation = true
  postSections = ["post", "book", "project", "machine learning"]
  # dateformat = "01.02.2016" # change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  # TL
  custom_css = ["css/tl.css","css/auto-complete.css"]
  highlight = true
  highlightStyle = "monokai-sublime"
  highlightLanguages = ["r", "python", "sql", "bash", "css", "ini", "javascript", "yaml", "markdown"]

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["taglist", "categories", "recent", "social"] #"search", 
  widgets_page = ["toc"]
[Params.widgets]
  recent_num = 10 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  linkedin = "thomas-laber"
  github = "thomaslaber"
  # email = "laber.thomas@gmail.com"

[outputs]
  home = [ "HTML", "RSS", "JSON"]